// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4-KmB5eD8LU3e37Cyns02p7G_fblUm3E',
    appId: '1:616696053472:web:0ad75dc5e3a68626885a85',
    messagingSenderId: '616696053472',
    projectId: 'home-rental-management-s-22a77',
    authDomain: 'home-rental-management-s-22a77.firebaseapp.com',
    storageBucket: 'home-rental-management-s-22a77.firebasestorage.app',
    measurementId: 'G-LH97V3Q7C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsNGIov2shYynQNHZc1CV0tHZ8H-4p1Q4',
    appId: '1:616696053472:android:ceec1d885c2551a7885a85',
    messagingSenderId: '616696053472',
    projectId: 'home-rental-management-s-22a77',
    storageBucket: 'home-rental-management-s-22a77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV4SwzWffyZGVtHm1lqk-GXx5TnkQDbw0',
    appId: '1:616696053472:ios:3c6257c954f4fdbe885a85',
    messagingSenderId: '616696053472',
    projectId: 'home-rental-management-s-22a77',
    storageBucket: 'home-rental-management-s-22a77.firebasestorage.app',
    iosBundleId: 'com.example.bashabondhuHomeRentalManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV4SwzWffyZGVtHm1lqk-GXx5TnkQDbw0',
    appId: '1:616696053472:ios:3c6257c954f4fdbe885a85',
    messagingSenderId: '616696053472',
    projectId: 'home-rental-management-s-22a77',
    storageBucket: 'home-rental-management-s-22a77.firebasestorage.app',
    iosBundleId: 'com.example.bashabondhuHomeRentalManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4-KmB5eD8LU3e37Cyns02p7G_fblUm3E',
    appId: '1:616696053472:web:5d93a846995b2440885a85',
    messagingSenderId: '616696053472',
    projectId: 'home-rental-management-s-22a77',
    authDomain: 'home-rental-management-s-22a77.firebaseapp.com',
    storageBucket: 'home-rental-management-s-22a77.firebasestorage.app',
    measurementId: 'G-LENDV9559W',
  );
}
